name = "Cardboard"
filename = "Cardboard-1.17-1.18.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/MLYQ9VGP/versions/1.17-43/Cardboard-1.17-1.18.jar"
hash-format = "sha1"
hash = "37336840a5994a548e718c512e001b0644cef4fc"

[update]
[update.modrinth]
mod-id = "MLYQ9VGP"
version = "PHkZ0Ydq"
