name = "EasyAuth"
filename = "easyauth-mc1.18-2.1.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/aZj58GfX/versions/1.18-2.1.0/easyauth-mc1.18-2.1.0.jar"
hash-format = "sha1"
hash = "4276c369be0d441b1695f41fe2bf7518321fce9c"

[update]
[update.modrinth]
mod-id = "aZj58GfX"
version = "Sfubmz7S"
