name = "Fabric Tailor"
filename = "fabrictailor-1.8.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/g8w1NapE/versions/1.8.0/fabrictailor-1.8.0.jar"
hash-format = "sha1"
hash = "7354fa8f60518eb25ec5a3a5778c34f30bbcb813"

[update]
[update.modrinth]
mod-id = "g8w1NapE"
version = "s0W061rZ"
