name = "Frameless"
filename = "frameless-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Kn67X8e6/versions/1.0.0/frameless-1.0.0.jar"
hash-format = "sha1"
hash = "1dd1b7f24842e63df892b8d9f9152bf8346376c2"

[update]
[update.modrinth]
mod-id = "Kn67X8e6"
version = "fVgJr6ME"
