name = "Hey That's Mine"
filename = "htm-1.1.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/IEPAK5x6/versions/1.1.4/htm-1.1.4.jar"
hash-format = "sha1"
hash = "9aea285613c4643a48f9506a95a086133ae4938d"

[update]
[update.modrinth]
mod-id = "IEPAK5x6"
version = "lGAQccSb"
