name = "Inv View"
filename = "InvView-1.4.8-1.18+.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/jrDKjZP7/versions/1.4.8/InvView-1.4.8-1.18+.jar"
hash-format = "sha1"
hash = "f225da7ae6b3327e36a017386d9d975c472a7303"

[update]
[update.modrinth]
mod-id = "jrDKjZP7"
version = "I4MXu784"
