name = "MiniMOTD"
filename = "minimotd-fabric-mc1.18-2.0.5.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/16vhQOQN/versions/2.0.5+1.18/minimotd-fabric-mc1.18-2.0.5.jar"
hash-format = "sha1"
hash = "d68b25c6c125234a10168749b2660984fc74cc9a"

[update]
[update.modrinth]
mod-id = "16vhQOQN"
version = "7OGxjN0L"
