name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-3.3.12+1.18.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/3.3.12+1.18.1/repurposed_structures_fabric-3.3.12%2B1.18.1.jar"
hash-format = "sha1"
hash = "401c16ef1de6c404e27183d50c61e9e30007e988"

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "4sr6Y94P"
