name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.32.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/699/voicechat-fabric-1.18.1-2.2.32.jar"
hash-format = "sha1"
hash = "f4fe38d218af48aa1c7025c70e974f980161c028"

[update]
[update.curseforge]
file-id = 3732699
project-id = 416089
